// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
import GoogleOAuthProvider from "./_components/google-oauth-provider";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider >
          {children}
        </GoogleOAuthProvider>

      </body>
    </html>
  )
}
